# config.yaml

logging:
  level: DEBUG
  file: code_quality_analyzer.log

report:
  default_type: html
  output_directory: results

analyzers:
  pylint: true
  flake8: true
  bandit: true
  mypy: true
  safety: true
  isort: true
  vulture: true
