# config.yaml

logging:
  level: DEBUG
  file: code_quality_analyzer.log

report:
  default_type: html
  output_directory: results

analyzers:
  pylint: true
  flake8: false
  bandit: false
  mypy: true
  safety: true
  isort: true
  vulture: true

pylint:
  disable_rules:
    - logging-fstring-interpolation

